# Generated by Django 5.1.5 on 2025-03-17 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
        ('minigames', '0003_game_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='game_url',
        ),
        migrations.AddField(
            model_name='location',
            name='game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='minigames.game'),
        ),
    ]
