# Generated by Django 5.1.5 on 2025-03-19 04:25

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_location_game_url_location_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=core.models.random_cat_image, upload_to='profile_pics/'),
        ),
    ]
