# Generated by Django 5.1.5 on 2025-03-19 04:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.CharField(default=core.models.random_cat_image, max_length=255),
        ),
    ]
