# Generated by Django 5.1.5 on 2025-03-19 04:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=core.models.random_cat_image, upload_to='profile_pics/'),
        ),
    ]
