# Generated by Django 5.1.5 on 2025-03-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_y_coordinate_location_x_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='game',
        ),
        migrations.AddField(
            model_name='location',
            name='minigame',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.minigame'),
        ),
    ]
