# Generated by Django 5.1.5 on 2025-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_minigame_remove_location_game_location_minigame'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_name',
            field=models.CharField(default='default_image.PNG', max_length=100),
            preserve_default=False,
        ),
    ]
