# Generated by Django 5.1.5 on 2025-03-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_location_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='minigame',
            name='intro_url_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
