# Generated by Django 5.1.7 on 2025-03-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0002_game_remove_gamescore_location_gamescore_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
            preserve_default=False,
        ),
    ]
