# Generated by Django 5.1.5 on 2025-03-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minigames', '0003_game_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
