# Generated by Django 5.1.7 on 2025-03-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='game_name',
            field=models.CharField(default='null_game_name', max_length=20),
            preserve_default=False,
        ),
    ]
