# Generated by Django 5.1.7 on 2025-03-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_location_game_name_location_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='game_url',
        ),
    ]
